### ISSUE TITLE
ncat not found on Ubuntu Xenial

### ISSUE THREAD

**Issue by SamyCoenen** [abaez/ansible-role-common#1]
it's one of the depends: ansible-role-common/defaults/main.yml

**Comment by abaez** [comment]
Hey @SamyCoenen, 

Thanks for the check over. I just noticed that the package for **ncat** is actually in **nmap** for Ubuntu and probably Debian. I'll do a fix on the listed query for the defaults to accommodate this.

As with the issue, I should have documented better, but you can also replace defaults with your own as was the reason for the defining the list in defaults instead of directly on the role's task.

**Comment by abaez** [comment]
I have to look over if it's worth the effort to add **nmap** instead for Debian based as this is a personal preference package and not necessarily a required dependency for common to function. 

I'm thinking of refactoring how `other_depend` are loaded with an option instead, since these are my own optional dependencies for the role.

In either case, I'm marking the issue closed for now. Thanks again for the input. Greatly appreciate it.
